apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: neerachal/deploy_febe_lppm:v0.2.3 # ใช้ Image บน Docker Hub
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort

# docker build -t neerachal/deploy_febe_lppm:v0.1.9 .
# docker push neerachal/deploy_febe_lppm:v0.1.9